--3)grupati comenzile (tabela tranzactii) efectuate in anul 2005 in functie de produse
create or replace PROCEDURE GRUPARE_COMENZI IS

CODE VARCHAR2(50);
MESSAGE VARCHAR2(512);
OBJECT_NAME VARCHAR2(50);
V_COD_PRODUSE PRODUSE.COD_PRODUS%TYPE;
V_DESCRIERE PRODUSE.DESCRIERE%TYPE;
V_NUMAR_VANZARI PRODUSE.COD_PRODUS%TYPE;

CURSOR EMP_CURSOR (AN NUMBER) IS SELECT PRODUSE.COD_PRODUS, PRODUSE.DESCRIERE, COUNT(TRANZACTII.COD_PRODUS) NUMAR_VANZARI 
                                    FROM PRODUSE
                                        LEFT JOIN TRANZACTII ON (PRODUSE.COD_PRODUS=TRANZACTII.COD_PRODUS)
                                            AND TO_CHAR(TRANZACTII.DATA_COMENZII,'YYYY')=TO_CHAR(AN)
                                                GROUP BY PRODUSE.COD_PRODUS, PRODUSE.DESCRIERE
                                                    ORDER BY  PRODUSE.COD_PRODUS;


BEGIN
    OPEN EMP_CURSOR (2005);
    LOOP
        FETCH EMP_CURSOR INTO V_COD_PRODUSE, V_DESCRIERE, V_NUMAR_VANZARI;
        EXIT WHEN EMP_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_COD_PRODUSE || ' ' || V_DESCRIERE || ' '|| TO_CHAR( V_NUMAR_VANZARI));
    END LOOP;
    CLOSE EMP_CURSOR;

    DBMS_OUTPUT.PUT_LINE('');

    OPEN EMP_CURSOR (2004);
    LOOP
        FETCH EMP_CURSOR INTO V_COD_PRODUSE, V_DESCRIERE, V_NUMAR_VANZARI;
        EXIT WHEN EMP_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_COD_PRODUSE || ' ' || V_DESCRIERE || ' '|| TO_CHAR( V_NUMAR_VANZARI));
    END LOOP;
    CLOSE EMP_CURSOR;

EXCEPTION
    WHEN OTHERS THEN

    OBJECT_NAME := 'AFISARE_DMBS' ;
    CODE :=SQLCODE;
    MESSAGE := SQLERRM(SQLCODE);

    INSERT INTO LOGS VALUES (SEQUENCE_LOGS.NEXTVAL, OBJECT_NAME, CODE, MESSAGE);
END GRUPARE_COMENZI;